name: build
on:
  push:
    branches:
      - master

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"         

      - name: Install Build + Test Dependencies (NumPy, Cython and PyYaml)
        run: pip install -r requirements-test.txt

      - name: Install Bitstream
        run: python setup.py --cython install
          
      - name: Run Tests
        run: python test.py          
