name: build
on:
  push:
    branches: [ master, new-setup ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"         

      - name: Install Bitstream
        run: pip install .
          
      - name: Install Test Dependency
        run: pip install pyyaml

      - name: Run Tests
        run: python test.py
        
      - name: Run Tests (verbose)
        run: python test.py --verbose